Scrum-29
utn-integrador-III/student-service-api pull request #13
Opened 2024-06-15 19:48 UTC by Ale021217

Creación de endpoint para actualizar la información de una zona en específico.

2024-06-17 14:28 UTC, ebarahonautn requested changes

2024-06-17 14:28 UTC, ebarahonautn commented on utils/message_codes.py
reemplazar INCORRECT_REQUEST_PARAM='COLUMN_NOT_FOUND' por
INCORRECT_REQUEST_PARAM='INCORRECT_REQUEST_PARAM'

2024-06-17 14:28 UTC, ebarahonautn commented on controllers/zonebyId/controller.py
@Ale021217 
- este PUT no va en el zonebyID controller, debe ir en el zone controller porque se va a llamar bajo el route /zone (ver la documentacion del swagger [http://localhost:5001/api/doc](http://localhost:5001/api/doc) 

-La linea 74 utilizar el message_code= INCORRECT_REQUEST_PARAM porque también esta validando que no vienen datos en el body.
- Linea 93 debe devolverse un BAD_REQUEST como estatuscode

2024-06-17 21:36 UTC, ebarahonautn approved these changes

2024-06-19 22:04 UTC, AnisanYT approved these changes
Excelente, todo lo requerido esta.

2024-06-19 23:09 UTC, merged