SC-33-Creación de endpoint CRUD de categoria de objetos perdidos
utn-integrador-III/student-service-api pull request #15
Opened 2024-06-15 22:48 UTC by JOSEEAND

2024-06-17 14:42 UTC, ebarahonautn requested changes

2024-06-17 14:42 UTC, ebarahonautn commented on controllers/category/controller.py
@JOSEEAND 
Modificar la línea 27 y 131, reemplazar zones por category

2024-06-17 17:11 UTC, ebarahonautn approved these changes

2024-06-19 22:03 UTC, AnisanYT approved these changes
Perfecto, todo bien.

2024-06-19 23:23 UTC, merged