Scrum-30: implementación endpoint para crear un nuevo reporte de objeto perdido
utn-integrador-III/student-service-api pull request #16
Opened 2024-06-21 05:49 UTC by dferreto

Se realizo el endpoint post de reporte de objeto perdido en controllers, models y message_codes

2024-06-21 18:01 UTC, AnisanYT requested changes, later dismissed
Por favor, no dejar comentarios en el código.

2024-06-21 21:15 UTC, dferreto commented
Los comentarios han sido eliminados

2024-06-21 21:31 UTC, ebarahonautn requested changes

2024-06-21 21:31 UTC, ebarahonautn commented on controllers/Lost_objects/controller.py
@dferreto 
el name no es criterio para verificar datos duplicados, de momento remover el siguiente codigo

object_exists = LostObjectModel.get_by_name(data.get("name"))
            if object_exists:
                return ServerResponse(message='Lost_object already exists', 
                                    message_code=LOST_OBJECTS_EXIST, status=StatusCode.CONFLICT)
                                    
  No poner quemado el correo de Marilyn y Yonan
el endpoint debe recibir un arreglo de correos en el safekeeper, o sea, debe venir en el request.get_json()

   data["safekeeper"] = [
                {"accepted": False, "user_email": "mmedina@utn.ac.cr"},
                {"accepted": False, "user_email": "yarguedas@utn.ac.cr"}
            ]

2024-06-21 22:12 UTC, dferreto commented on controllers/Lost_objects/controller.py
Object_exists eliminado. Ahora quedo al tanto del safekeeper

2024-06-22 02:05 UTC, ebarahonautn approved these changes

2024-06-22 02:09 UTC, KennethStoneP approved these changes
todo bien!

2024-06-22 02:23 UTC, ebarahonautn approved these changes

2024-06-22 02:24 UTC, merged