Scrum-63
utn-integrador-III/student-service-api pull request #17
Opened 2024-06-22 00:58 UTC by Ale021217

Revisión y correción del swagger de post y put de zones

2024-06-24 16:06 UTC, ebarahonautn requested changes

2024-06-24 16:06 UTC, ebarahonautn commented on swagger.yml
@Ale021217 

Revisar y arreglar el error en swagger.yml

![Screenshot 2024-06-24 at 10 05 36 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/a89d4155-aff2-4efb-9947-0b31d6f43d77)

2024-06-25 13:06 UTC, ebarahonautn approved these changes

2024-06-25 14:12 UTC, XxKeyDarkxX approved these changes

2024-06-25 17:10 UTC, merged