Scrum 61
utn-integrador-III/student-service-api pull request #18
Opened 2024-06-22 02:43 UTC by LilMat69

=================================================
**Errors Found**: 
**Error Message**: "ERROR:root:Object of type ObjectId is not JSON serializable"
**At**: controllers/Lost_objects/controller.py
**Fixed issue Evidence**: 
<img width="697" alt="image" src="https://github.com/utn-integrador-III/student-service-api/assets/137030331/4c156df3-0849-4acd-8077-9b0c2db458f1">
==================================================
**Swagger Modification**: Modifying the complete CRUD for LostObjects and generating al the CRUD for Categories, according to the data structured from the database.
**Evidence**:
<img width="1426" alt="image" src="https://github.com/utn-integrador-III/student-service-api/assets/137030331/a4d23f38-526b-44f5-a60e-c900077fc322">
<img width="1278" alt="image" src="https://github.com/utn-integrador-III/student-service-api/assets/137030331/59855cde-64cb-4bc5-8392-712ca06c51b4">

2024-06-24 15:59 UTC, ebarahonautn approved these changes

2024-06-25 03:43 UTC, AnisanYT requested changes
Revisar los comentarios en el código, @LilMat69 , gracias, solicitar revisión para la notificación y realizar las revisiones después de las correcciones.

2024-06-25 03:43 UTC, AnisanYT commented on swagger.yml
> +      userID:
@LilMat69 , basarse en el formato que esta en la base de datos, userID debería de ser user_email:

![image](https://github.com/utn-integrador-III/student-service-api/assets/114460329/93e5ffd1-189f-492f-8b4a-4530db61a7f2)

Revisar esto, por favor.

2024-06-25 03:48 UTC, LilMat69 commented on swagger.yml
> +      userID:
Done
![image](https://github.com/utn-integrador-III/student-service-api/assets/137030331/71b1a040-77a9-48ca-b570-1199d4c5817b)

2024-06-25 03:53 UTC, AnisanYT commented on swagger.yml
> +      userID:
Muchas gracias, @LilMat69 .

2024-06-25 03:53 UTC, AnisanYT approved these changes
Excelente, @LilMat69 , muchas gracias, todo bien.

2024-06-25 03:54 UTC, merged