SCRUM-62
utn-integrador-III/student-service-api pull request #19
Opened 2024-06-22 04:36 UTC by Remma27

https://ever-utn.atlassian.net/browse/SCRUM-62?atlOrigin=eyJpIjoiMjYzYjljODMyZDFhNGYyYTgwMTUwYjAyNjVkOTMzMjAiLCJwIjoiaiJ9

2024-06-24 15:53 UTC, ebarahonautn requested changes

2024-06-24 15:53 UTC, ebarahonautn commented on swagger.yml
@Remma27 
Revisar, arreglar y asegurar que el swagger.yml este actualizado con respecto a los endpoints.

![Screenshot 2024-06-24 at 9 52 01 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/e3887cbf-bc0d-4b64-8831-74ffe144fabf)

2024-06-25 02:38 UTC, ebarahonautn requested changes

2024-06-25 02:38 UTC, ebarahonautn commented on swagger.yml
@Remma27 
POST endpoint replace _description_ by **location**

![Screenshot 2024-06-24 at 8 37 33 PM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/ed6dcc69-aabc-4599-99f9-e8d62d868f02)

2024-06-25 04:29 UTC, ebarahonautn commented on swagger.yml
PR tiene conflictos

2024-06-27 02:37 UTC, ebarahonautn approved these changes

2024-06-27 02:37 UTC, ebarahonautn commented on swagger.yml
@Remma27 

Please change the current response for GetAll and GetbyId with the correct attributes and check the conflict in the PR.

{
      "_id": "0183IEHU#&#J",
      "name": "Laboratories",
      "location": "Laboratories Zone"
    }

![Screenshot 2024-06-25 at 5 02 02 PM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/7e3b361a-58d5-48e1-9d32-4ef21bc1c6a6)
![Screenshot 2024-06-25 at 5 02 18 PM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/8d1196a2-7531-4c60-8b09-71452e4a00f5)

2024-06-28 15:13 UTC, XxKeyDarkxX approved these changes

2024-06-28 16:50 UTC, merged