SC-59
utn-integrador-III/student-service-api pull request #20
Opened 2024-06-24 03:14 UTC by JhonAllen01

Verificación de métodos dentro del controlador para Categorías y actualización con nueva modal para Categorías dentro de swagger, con sus respectivas definiciones.

2024-06-26 23:44 UTC, ebarahonautn requested changes

2024-06-26 23:44 UTC, ebarahonautn commented on controllers/category/controller.py
@JhonAllen01 
Realizar los siguientes ajustes:

### **GetAll de category**

Reemplazar StatusCode.OK por BAD_REQUEST

```
return ServerResponse(
                    data={},
                    message="No categories found",
                    message_codes=NO_DATA,
                    status=StatusCode.BAD_REQUEST,
                )
```
![Screenshot 2024-06-24 at 10 19 46 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/ca9c9cb1-1b75-47e1-be13-51df37d16a16)

______________________________________________________________________________________

### **Controller By id**

**Delete**
Modificar StatusCode.OK por StatusCode.BAD_REQUEST

```
return ServerResponse(
                    data={},
                    message="The category does not exist and cannot be deleted.",
                    message_code=NO_DATA,
                    status=StatusCode.BAD_REQUEST,
                )
```

![Screenshot 2024-06-24 at 10 15 59 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/6de8d677-77bb-478b-9ad7-e5f349fef921)

______________________________________________________________________________________

**PUT**
En el else modificar el responde de StatusCode.NOT_FOUND por StatusCode.BAD_REQUEST

```
return ServerResponse(
                    data={},
                    message="Category not found or category already exists",
                    message_code=NO_DATA,
                    status=StatusCode.BAD_REQUEST,
                )
```

En el catch de la exception eliminar el mensaje de error: message="Category not found or category already exists."
```
return ServerResponse(
                data={},
                message_code=NO_DATA,
                status=StatusCode.INTERNAL_SERVER_ERROR,
            )
```

![Screenshot 2024-06-24 at 10 16 51 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/32db39b9-249d-468c-bb58-8cc153ea678b)

______________________________________________________________________________________

**Get by Id**
En el else modificar el responde de StatusCode.OK por StatusCode.BAD_REQUEST

```
return ServerResponse(
                    data={},
                    message="Category does not exist",
                    message_code=NO_DATA,
                    status=StatusCode.OK,
                )
```


![Screenshot 2024-06-24 at 10 18 06 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/8cc77f22-2292-4a80-9541-31f8450aac6a)

2024-06-27 01:57 UTC, AnisanYT approved these changes
Listo!

2024-06-28 16:47 UTC, ebarahonautn requested changes

2024-06-28 16:47 UTC, ebarahonautn commented on swagger.yml
@JhonAllen01 
Por favor solucionar los siguiente en el swagger.yml

Hay un error en la linea 400
![Screenshot 2024-06-28 at 10 43 52 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/0c5bc85b-0d88-41c8-93a8-b3b8c430d3f6)


El get all debe devolver en el response una lista de categorias
![Screenshot 2024-06-28 at 10 43 34 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/7031dba8-180f-42e4-8b42-0989d0025458)

```
"data": [
      {
          "_id": "238H$Fj3KJD",
          "name": "Celulares"
        },
        {
          "_id": "238H$UBOD",
          "name": "Articulo oficina"
        }
  ]
```

2024-06-28 17:30 UTC, JhonAllen01 commented on swagger.yml
@ebarahonautn Profe, buenos dias.

Sucede que la linea 400 que usted me indica no es la misma que aparece en mi archivo swagger.yml
![E3](https://github.com/utn-integrador-III/student-service-api/assets/125415438/386d64bb-2a29-4f73-96f4-e15c6e0af5a9)

Yo revise nuevamente la seccion de categoryGet que en mi caso es la linea 103 y no me aparece ningun error, pero de igual forma probé el metodo getAll en el swagger y en efecto refleja una lista de datos(aunque en este caso particular unicamente muestra solo 1)
![image](https://github.com/utn-integrador-III/student-service-api/assets/125415438/87c10f2c-0992-4947-b6bb-70b6ea7d3157)

asi se muestra dentro de la pagina swagger
![image](https://github.com/utn-integrador-III/student-service-api/assets/125415438/37de6c47-f5bb-430a-b56c-8e39e1bc9cd0)


Por favor, hacerme saber si los datos reflejados deberian mostrarse de otra forma para asi corregirlo.

2024-06-29 01:42 UTC, ebarahonautn approved these changes

2024-06-29 01:42 UTC, merged