SCRUM-66 Create LostObject getById endpoint
utn-integrador-III/student-service-api pull request #21
Opened 2024-06-26 17:25 UTC by JOSEEAND

2024-06-27 00:57 UTC, AnisanYT approved these changes
Excelente. Gracias @JOSEEAND

2024-06-28 17:06 UTC, ebarahonautn requested changes

2024-06-28 17:06 UTC, ebarahonautn commented on controllers/Lost_objectsbyId/controller.py
@JOSEEAND 
StatusCode debe ser BAD_REQUEST y messageCode.NO_DATA


Incorrecto:

```
return ServerResponse(
                    data={},
                    message=LOST_OBJECTS_NOT_FOUND,
                    message_code=NO_DATA,
                    status=StatusCode.NOT_FOUND,
```
                )

**Correcto**:
```
return ServerResponse(
                    data={},
                    message=LOST_OBJECTS_NOT_FOUND,
                    message_code=NO_DATA,
                    status=StatusCode.BAD_REQUEST,
                )
```

2024-06-28 23:18 UTC, ebarahonautn requested changes
Arreglar los conflictos en el PR

2024-06-29 00:13 UTC, ebarahonautn approved these changes

2024-06-29 00:13 UTC, merged