SCRUM-67  Create put endpoint to lost object: editar resumen Create put endpoint to lost object
utn-integrador-III/student-service-api pull request #22
Opened 2024-06-26 20:48 UTC by edduardaq

2024-06-28 17:20 UTC, ebarahonautn requested changes

2024-06-28 17:20 UTC, ebarahonautn commented on .env.example
@edduardaq 
Este archivo no se debe borrar, por favor restaurelo

2024-06-28 17:20 UTC, ebarahonautn commented on controllers/Lost_objects/controller.py
@edduardaq 
En el put no debe enviarse el id por el url, todo biene en el body, revise el swagger.yml. Realizar los ajustes.

2024-06-30 07:02 UTC, LilMat69 commented
The put route must be on the 'lost_objectsbyid' folder, please resolve conflicts with github directly or make a pull from dev branch and resolve them locally!

2024-07-08 03:42 UTC, LilMat69 commented
Very good

2024-07-09 17:23 UTC, ebarahonautn requested changes

2024-07-09 17:23 UTC, ebarahonautn commented on controllers/lost_objectsbyid/controller.py
@edduardaq el put debe ir en el archivo controllers/Lost_objects/controller.py por pasarlo.

2024-07-09 17:23 UTC, ebarahonautn commented on controllers/lost_objectsbyid/parser.py
@edduardaq pasar el parserpy a controllers/Lost_objects/ para que el put lo identifique.

2024-07-09 17:23 UTC, ebarahonautn commented on service.py
@edduardaq remover **api.add_resource(LostObjectByIdController, LostObjectByIdController.route)** porque el put se debe pasar a **controllers/Lost_objects/controller.py**

2024-07-10 03:49 UTC, XxKeyDarkxX approved these changes

2024-07-10 03:59 UTC, GenVallejo approved these changes

2024-07-11 00:02 UTC, ebarahonautn approved these changes

2024-07-11 00:02 UTC, merged