SC-121 Modify Put Endpoint for Student-service-api
utn-integrador-III/student-service-api pull request #30
Opened 2024-07-21 22:26 UTC by JOSEEAND

changes in service.py were bad syntax

2024-07-21 22:30 UTC, LilMat69 requested changes
Please add proper evidence of the method to make sure that runs properly

2024-07-22 15:10 UTC, ebarahonautn requested changes
@JOSEEAND please add screnshot that it runs properl.

2024-07-23 17:44 UTC, ebarahonautn requested changes

2024-07-23 17:44 UTC, ebarahonautn commented on controllers/categorybyId/controller.py
@JOSEEAND 
change this `@auth_required(permission="delete_category", with_args=True)`

by **`@auth_required(permission="delete", with_args=True)`**

2024-07-24 14:21 UTC, JOSEEAND commented on controllers/categorybyId/controller.py
changes ready

2024-07-26 16:26 UTC, ebarahonautn approved these changes

2024-07-26 16:26 UTC, merged