LostObject with Categories
utn-integrador-III/student-service-api pull request #33
Opened 2024-07-30 15:22 UTC by Remma27

Hice los cambios en el post y put de Lost Object para recibir por el cuerpo un array de categorias. 

![post](https://github.com/user-attachments/assets/196cc811-6f7f-4a17-b7a2-4220df4ea3a6)
![put](https://github.com/user-attachments/assets/008fdcd1-0cbb-4c62-b8ee-4d360c6fdaaa)

Quedo pendiente a cualquier cambio en caso de ser necesario

2024-08-01 05:27 UTC, Remma27 commented on controllers/Lost_objects/controller.py
> +            }
Imagino que son campos requeridos pero no hay espacio en el insert del frontend para agregarlos

2024-08-03 18:09 UTC, ebarahonautn requested changes

2024-08-03 18:09 UTC, ebarahonautn commented on controllers/category/controller.py
@Remma27 post and put require token validation, please enable it

2024-08-03 18:09 UTC, ebarahonautn commented on controllers/category/controller.py
@Remma27 post and put need token validation, please enable it

2024-08-03 18:09 UTC, ebarahonautn commented on swagger.yml
@Remma27 include _id property in the body in put endpoint

![Screenshot 2024-08-03 at 12 08 46 PM](https://github.com/user-attachments/assets/cb6de432-46eb-42a3-b142-e9d2703b704a)

2024-08-05 16:11 UTC, ebarahonautn approved these changes

2024-08-05 16:11 UTC, merged