Scrum 144 - PATCH endpoint to modify the lostbObject Status
utn-integrador-III/student-service-api pull request #34
Opened 2024-08-09 17:56 UTC by JOSEEAND

[evidences.pdf](https://github.com/user-attachments/files/16565174/evidences.pdf)

2024-08-09 19:38 UTC, LilMat69 requested changes
Please add this endpoint to the swagger file, remember the authorization header in the swagger as well for the permissions

2024-08-09 21:06 UTC, JOSEEAND commented
![image](https://github.com/user-attachments/assets/8fb97f33-5f21-41fb-827b-72bc8500b651)

2024-08-10 02:15 UTC, LilMat69 requested changes

2024-08-10 02:15 UTC, LilMat69 commented on swagger.yml
Add the following messages into swagger: 

![image](https://github.com/user-attachments/assets/60d35554-4464-47b3-aa10-6888d9cb236c)

![image](https://github.com/user-attachments/assets/55a27a9e-613b-4c54-944b-fe0c6c8076b9)

2024-08-14 17:35 UTC, JOSEEAND commented on swagger.yml
![image](https://github.com/user-attachments/assets/6233bd38-2f39-4bcc-a134-cad31f1d7444)

2024-08-14 17:48 UTC, LilMat69 approved these changes

2024-08-14 17:48 UTC, merged