US-046
utn-integrador-III/student-service-api pull request #4
Opened 2024-06-11 21:56 UTC by LilMat69

2024-06-11 22:09 UTC, LilMat69 commented
[
![Captura de pantalla 2024-06-11 a las 4 07 33 p  m](https://github.com/utn-integrador-III/student-service-api/assets/137030331/1b8af54a-4476-4fac-9633-9e9ee63bea4e)
![Captura de pantalla 2024-06-11 a las 4 07 54 p  m](https://github.com/utn-integrador-III/student-service-api/assets/137030331/2c2f7d9e-4597-494c-834e-b40b4a687b6c)
![Captura de pantalla 2024-06-11 a las 4 08 05 p  m](https://github.com/utn-integrador-III/student-service-api/assets/137030331/115afe0d-7091-4e73-aaa5-93a18d3738c8)
](url)

2024-06-12 14:03 UTC, ebarahonautn requested changes
@LilMat69 @KennethStoneP 

- A todos los endpoints que son PUT no reciba el id en el url, por ejemplo, el put de zonas está definido como /zone/{zoneId} lo correcto sería /zone el id tiene que venir en los parámetros dentro del body del request. Realizar este cambio a todos los PUT de eliminar el {id} en la ruta del endpoint
- Tambien verificar que todos los endpoint PUT dentro de la información enviada en el body venga tambien el atributo **_id** que es el objectId generado por la BD para cada documento.

![Screenshot 2024-06-12 at 7 59 16 AM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/0c777fdd-4025-48f4-8bb3-1527dcfe0c47)

2024-06-12 15:39 UTC, LilMat69 commented
Con respecto a lo requerido para los endpoint de PUT, esto aplica también para el DELETE y el GETByID?

2024-06-12 19:05 UTC, LilMat69 commented
Cambios hechos @ebarahonautn, favor revisar

2024-06-13 00:07 UTC, ebarahonautn approved these changes

2024-06-13 00:08 UTC, dferreto approved these changes

2024-06-13 00:08 UTC, merged