endpoint delete
utn-integrador-III/student-service-api pull request #6
Opened 2024-06-12 17:36 UTC by JOSEEAND

2024-06-12 19:53 UTC, ebarahonautn requested changes

2024-06-12 19:53 UTC, ebarahonautn commented on models/zone/model.py
@JOSEEAND @JhonAllen01 

El modelo no debe devolver los mensajes que van a ser respondido hacia el frontend, por lo tanto, debe cambiar la logica que solo indique si se eliminó o nó la zona. Para el catch que haga un raise de la excepción.

En resumen, eliminar los textos de mensajes de devuelve el metodo delete en el modelo.

![Screenshot 2024-06-12 at 1 05 07 PM](https://github.com/utn-integrador-III/student-service-api/assets/80927814/be969a53-4080-448b-bc15-b13f5443a287)

2024-06-12 19:53 UTC, ebarahonautn commented on db/mongo_client.py
En el mongo_client.py el catch del metodo detele_data() realice un raise de la excepcion en lugar de devolver un texto.

poner raise ex dentro del catch

2024-06-12 19:53 UTC, ebarahonautn commented on controllers/zonebyId/controller.py
@JOSEEAND @JhonAllen01 

El metodo delete debe validar si el modelo realizó o no la eliminación segun a la respuesta que devuelva el modelo.

En el escenario actual el response siempre va ser status OK aunque el delete no se haya realizado. Por lo tanto, es importante validar y si no se genera el delete, indicar un mensage segun la validacion:

1- Si el delete no se realizar porque la zona no existe:
mensaje en el response: return ServerResponse(data={}, message="The zone no exists and cannot be deleted.", message_codes=NO_DATA, status=StatusCode.OK)

2- Si el delete es realizado el response es: 
return ServerResponse(message='Zone successfully deleted',  message_code=ZONE_SUCCESSFULLY_DELETED, status=StatusCode.OK)

3- en caso que el controller obtenga una excepcion, dentro del catch respoder lo siguiente:
            logging.exception(ex)
            return ServerResponse(status=StatusCode.INTERNAL_SERVER_ERROR)

2024-06-13 16:07 UTC, ebarahonautn approved these changes

2024-06-14 08:38 UTC, dferreto approved these changes

2024-06-14 14:46 UTC, merged