US-019 Implementar el enpoint para listar todos os objetos perdidos API OP
utn-integrador-III/student-service-api pull request #9
Opened 2024-06-13 05:23 UTC by edduardaq

2024-06-13 16:55 UTC, ebarahonautn requested changes

2024-06-13 16:55 UTC, ebarahonautn commented on .env.example
@edduardaq  @DevWilliamCN 
Quitar solamente el string the conexion ya que el repo es publico, no queremos que alguien de afuera accese a nuestra BD.

dejar la variable MONGO_URL=

2024-06-13 16:55 UTC, ebarahonautn commented on .vscode/launch.json
@edduardaq @DevWilliamCN 
no subir este launch.json

2024-06-13 16:55 UTC, ebarahonautn commented on controllers/Lost_objects/controller.py
@edduardaq @DevWilliamCN 
- Quitar el codigo comentado de la linea 1: # controllers/lost_objects/controller.py

2024-06-13 16:55 UTC, ebarahonautn commented on data-model-script.txt
@edduardaq @DevWilliamCN  
Este archivo data-model-script.txt está correcto en dev, seguro realizaron mal el merge. por favor excluirlo del push. Este archivo no debe ser parte de su commit y push.

2024-06-13 16:55 UTC, ebarahonautn commented on db/db_manager.py
@edduardaq  @DevWilliamCN 
Este archivo ya no existe en el branch de dev y no se va a usar más. Por favor excluirlo del PR.

2024-06-13 16:55 UTC, ebarahonautn commented on package-lock.json
@edduardaq @DevWilliamCN 
Omitir este archivo del PR

2024-06-13 16:55 UTC, ebarahonautn commented on service.py
@edduardaq @DevWilliamCN 
Las lineas 18 y 20 estan repetidas, por favor dejar solamente una linea.

2024-06-14 19:35 UTC, dferreto approved these changes

2024-06-15 00:42 UTC, ebarahonautn approved these changes

2024-06-15 00:42 UTC, ebarahonautn commented on controllers/Lost_objects/controller.py
@DevWilliamCN  @edduardaq 
eliminar el codigo de la linea #1:

`controllers/lost_objects/controller.py`

2024-06-15 00:42 UTC, ebarahonautn commented on controllers/Lost_objects/parser.py
@edduardaq @DevWilliamCN 
Borrar el codigo comentado de la linea #1

`# controllers/lost_objects/parser.py`

2024-06-15 00:44 UTC, merged